import type { WikiGraph, WikiNode } from "./types.js";

const id = (value: string) => `n_${value.replace(/[^A-Za-z0-9_]/g, "_")}`;
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

export function graphToMermaid(graph: WikiGraph, focus?: WikiNode): string {
  const lines = [
    "%% Generated by LLM Wiki Canvas from resolved Markdown relationships.",
    ...(focus ? [`%% Focus: ${focus.path}`] : []),
    "flowchart LR",
  ];
  for (const node of graph.nodes) {
    lines.push(`  ${id(node.id)}["${escape(node.title)}<br/>${escape(node.path)}"]:::${node.kind}`);
  }
  for (const edge of graph.edges) {
    const label = escape(edge.label ? `${edge.kind}: ${edge.label}` : edge.kind);
    lines.push(`  ${id(edge.source)} -->|"${label}"| ${id(edge.target)}`);
  }
  for (const diagnostic of graph.diagnostics.filter((item) => item.code === "BROKEN_LINK")) {
    lines.push(`  %% BROKEN_LINK ${diagnostic.path} -> ${diagnostic.target ?? "unknown"}`);
  }
  lines.push(
    "  classDef index fill:#e8edff,stroke:#3159e8,stroke-width:3px,color:#17201b",
    "  classDef concept fill:#edf0ff,stroke:#6477d8,stroke-width:2px,color:#17201b",
    "  classDef source fill:#fff2d9,stroke:#c47c16,stroke-width:2px,color:#17201b",
    "  classDef note fill:#f5f7f4,stroke:#66716a,stroke-width:2px,color:#17201b",
  );
  if (focus) lines.push(`  class ${id(focus.id)} focus`, "  classDef focus stroke:#173fc5,stroke-width:4px");
  return `${lines.join("\n")}\n`;
}
